workflow: update scorecard.yml

diff --git a/.github/workflows/scorecard.yml b/.github/workflows/scorecard.yml
--- a/.github/workflows/scorecard.yml
+++ b/.github/workflows/scorecard.yml
@@ -35,28 +35,35 @@ jobs:
       id-token: write
     steps:
       - name: "Checkout code"
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
+        uses: actions/checkout@v4
         with:
           persist-credentials: false
 
       - name: "Run analysis"
-        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736
+        uses: ossf/scorecard-action@v4
         with:
           results_file: results.sarif
           results_format: sarif
           publish_results: true
+          log_level: debug  # Daha detaylı log al
 
-      - name: Check if SARIF file exists
-        run: ls -lah ./sarif-results/
+      - name: "Check Scorecard output"
+        run: cat results.sarif || echo "SARIF output not generated"
+
+      - name: "Debug: Check if results.sarif exists"
+        run: ls -lah results.sarif || echo "results.sarif NOT FOUND"
 
       - name: "Upload artifact"
-        uses: actions/upload-artifact@97a0fba1372883ab732affbe8f94b823f91727db
+        uses: actions/upload-artifact@v4
         with:
-          name: sariffile
-          path: ./sarif-results/**/*.sarif
+          name: es-query-builder-sarif
+
+          path: results.sarif
           retention-days: 5
 
       - name: "Upload to code-scanning"
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: results.sarif
+
+
